<style>
	h5 {color:blue}
</style>

<?php 
	echo $this->form()->openTag($this->form);
	
	echo '<h5>Zend\Form\Element\Number</h5>';
	echo $this->formRow($this->form->get('my-number'));
	
	echo '<h5>Zend\Form\Element\Color</h5>';
	echo $this->formRow($this->form->get('my-color'));
	
	echo '<h5>Zend\Form\Element\Date</h5>';
	echo $this->formRow($this->form->get('my-date'));
	
	echo '<h5>Zend\Form\Element\Email</h5>';
	echo $this->formRow($this->form->get('my-email'));
	
	echo '<h5>Zend\Form\Element\Range</h5>';
	echo $this->formRow($this->form->get('my-range'));
	
	echo '<h5>Zend\Form\Element\Submit</h5>';
	echo $this->formRow($this->form->get('my-submit'));
	
	echo $this->form()->closeTag();
?>