<!DOCTYPE html>
<html>
<head>
<meta charset="${encoding}">
<title>Insert title here</title>
</head>
<body>
    <h1>index4.phtml</h1>
    
    <div>
       {% set x = 30 %}
       {% set y = 10 %}
    </div>
    
   
    
    <hr>
    <div>
        x > y :    {{ x > y }}<br>
        x < y :    {{ x < y }}<br>
        x <> y :   {{ x <> y }}<br>
        x != y :   {{ x != y }}<br>
        x == y :   {{ x == y }}<br>
        x === y :  {{ x === y }}<br>
        x !== y :  {{ x !== y }}<br>
         x <= y :  {{ x <= y }}<br>
         x >= y :  {{ x >= y }}<br>
       
    </div>
    
</body>
</html>