<!DOCTYPE html>
<html>
<head>
<meta charset="${encoding}">
<title>Insert title here</title>
</head>
<body>
   {% set arr_keys   = ['peter':30, 'nam':20, 'mary':10, 'luna': 60] %}
   {% set arr_keys2  = arr_keys | keys %}
   
    
   <b>Before filter keys</b><br> 
   {% for key, value in arr_keys %}
        {{ key }} -- {{ value }}<br>
   {% endfor %}
   <hr>
   
   <b>After filter keys</b><br> 
   {% for key, value in arr_keys2 %}
        {{ key }} -- {{ value }}<br>
   {% endfor %}
   <hr>
   
  
    
    
    
    
    
</body>
</html>