<!DOCTYPE html>
<html>
<head>
<meta charset="${encoding}">
<title>Insert title here</title>
<style type="text/css">
.successMessage
{
	background-color:green;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}
.errorMessage
{
	background-color:red;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}
.noticeMessage
{
	background-color:blue;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}

.warningMessage
{
	background-color:orange;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}
</style>
</head>
<body>
    <h1>Direct 2</h1>
    
    <?php 
        $direct = new \Phalcon\Flash\Direct();
        
        $direct->outputMessage('success', 'this is success message 2');
        $direct->outputMessage('error', 'this is error message 2');
        $direct->outputMessage('notice', 'this is notice message 2');
        $direct->outputMessage('warning', 'this is warning message 2');
        $direct->outputMessage('abc', 'complex message 2');
        
       
    ?>
</body>
</html>