<!DOCTYPE html>
<html>
<head>
<meta charset="${encoding}">
<title>Insert title here</title>
<style type="text/css">
.successMessage
{
	background-color:green;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}
.errorMessage
{
	background-color:red;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}
.noticeMessage
{
	background-color:blue;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}

.warningMessage
{
	background-color:orange;
	color:white;
	margin:0px auto;
	margin-bottom:25px;
	width:250px;
}
</style>
</head>
<body>
    <h1>Direct</h1>
    
    <?php 
        $direct = new \Phalcon\Flash\Direct();
        
        $this->flash->success('this is success message');
        $this->flash->error('this is error message');
        $direct->notice('this is notice message');
        $direct->warning('this is warning message');
       
    ?>
</body>
</html>