<style>
	h5 {color:blue}
</style>

<?php 
	// FormRow 	= FormLabel + FormInput (FormElement) + FormElementErrors
	// FormText	= FormInput (FormElement)
	
	$myForm	= $this->myForm;
	echo $this->form()->openTag($this->myForm);
	
	echo '<h5>Zend\Form\Element\Text</h5>';
	echo '<br />' .$this->formText($myForm->get('my-textbox'));
	
	echo '<h5>Zend\Form\Element\Number</h5>';
	echo $this->formNumber($myForm->get('my-number'));
	
	echo '<h5>Zend\Form\Element\Password</h5>';
	echo $this->formPassword($myForm->get('my-password'));
	
 	echo '<h5>Zend\Form\Element\Textarea</h5>';
 	echo $this->formTextarea($myForm->get('my-textarea'));
	
	echo '<h5>Zend\Form\Element\Button</h5>';
	echo $this->formButton($myForm->get('my-button'));
	echo $this->formButton()->render($myForm->get('my-button'), 'My Submit form');
	echo $this->formButton()->render($myForm->get('my-button'), '<span>My Submit form</span>');
	
	echo $this->formButton()->openTag($myForm->get('my-button'));
		echo '<span>My button</span>';
	echo $this->formButton()->closeTag();
	
// 	echo '<h5>Zend\Form\Element\File</h5>';
// 	echo $this->formRow($myForm->get('my-file'));
	
// 	echo '<h5>Zend\Form\Element\Checkbox</h5>';
// 	echo $this->formRow($myForm->get('my-checkbox'));
	
// 	echo '<h5>Zend\Form\Element\MultiCheckbox</h5>';
// 	echo $this->formRow($myForm->get('my-multicheckbox'));
	
// 	echo '<h5>Zend\Form\Element\Submit</h5>';
// 	echo $this->formRow($myForm->get('my-submit'));
	
	echo $this->form()->closeTag();
?>


