<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
        {% block header %}
            <div>Header content - parent - main2.phtml</div>
        {% endblock %}
        
        <hr>
        
        {% block middle %}
            <div>Middle content - parent - main2.phtml</div>
        {% endblock %}
        
        <hr> 
        {% block footer %}
            <div>Footer content - parent - main2.phtml</div>
        {% endblock %}
        
		
		
		
		<!-- Đây là phần nội dung của tập tin main.phtml -->
</body>
</html>