<?php 
	echo $this->partial('course.phtml', array(
		'name'			=> 'Khóa học lập trình jQuery',
		'description'	=> 'Nếu nói đến lập trình web, chúng ta nghĩ ngay đến một ngôn ngữ lập trình không thể thiếu trong một website đó là Javascript. Javascript giúp chúng ta thực hiện nhưng thao tác, hiệu ứng mà các ngôn ngữ lập web như PHP, ASP, JSP… khó mà thực hiện được. ',
		'style'			=> array(
			'color'				=> 'red',
		)
	));

?>