<?php 
	echo $this->partial('course.phtml', array(
		'name'			=> 'Khóa học lập trình PHP',
		'description'	=> 'PHP đã và đang trở thành một ngôn ngữ lập trình phổ biến trong các ứng dụng web ngày nay. Với các ưu điểm như miễn phí, dễ đọc, thao tác tốt với các hệ quản trị cơ sở dữ liệu, cộng đồng sử dụng rộng rãi, thư viện phong phú ...',
		'style'			=> array(
			'color'				=> 'red',
			'text-decoration'	=> 'underline',
		)
	));

?>