<!DOCTYPE html>
<html>
<head>
<meta charset="${encoding}">
<title>Insert title here</title>
</head>
<body>
    <h1> form post - get</h1>
    <form action="/post-router" method="post">
        <input type="submit" value="post-form">
    </form>
    
     <form action="/get-router" method="get">
        <input type="submit" value="get-form">
    </form>
    
     <form action="/via-post" method="post">
        <input type="submit" value="via-form">
    </form>
</body>
</html>