<?php 
	$myForm				= $this->myForm;
	$myForm->prepare();
	$elementEmail		= $myForm->get('my-email');
	$elementPassword	= $myForm->get('my-password');
	$elementCheckbox	= $myForm->get('my-checkbox');
	$elementBtnSubmit	= $myForm->get('my-button-submit');
	$elementBtnReset	= $myForm->get('my-button-reset');
	
	$elements		= array(
			array(
					'label'	=> $this->formLabel($elementEmail),
					'input'	=> $this->formElement($elementEmail),
					'class'	=> 'col-sm-9',
					'error'	=> $this->elementErrorIcon($elementEmail),
			),
			array(
					'label'	=> $this->formLabel($elementPassword),
					'input'	=> $this->formElement($elementPassword),
					'class'	=> 'col-sm-9',
					'error'	=> $this->elementErrorIcon($elementPassword),
			),
			array(
					'label'	=> null,
					'input'	=> '<div class="checkbox">' .$this->formLabel($elementCheckbox, $this->formElement($elementCheckbox), 'append') . '</div>',
					'class'	=> 'col-sm-9 col-sm-offset-3',
			),
			array( 
					'label'	=> null,
					'input'	=> $this->formElement($elementBtnSubmit) . ' ' . $this->formElement($elementBtnReset),
					'class'	=> 'col-sm-offset-3 col-sm-9',
			),
	);
?>
<script type="text/javascript">
	$(function(){
			$('[data-toggle=tooltip]').tooltip({
				html		: true,
				placement	: 'right',
			});
	});

</script>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-lock"></span>Login
			</div>
			<div class="panel-body">
			<?php 
				echo $this->form()->openTag($myForm);
					echo $this->partialLoop('form-group.phtml', $elements);
				echo $this->form()->closeTag();
			?>
			</div>
			<div class="panel-footer">
				Not Registred? <a href="http://www.jquery2dotnet.com">Register here</a>
			</div>
		</div>
	</div>
</div>