<!DOCTYPE html>
<html>
<head>
<meta charset="${encoding}">
<title>Insert title here</title>
</head>
<body>
        <h1>index.phtml</h1>
        {%  set colors = ['red':'màu đỏ', 'green':'màu xanh lá', 'blue': 'màu xanh dương'] %}
        
        <div>
            red     = {{ colors['red'] }}<br>
            green   = {{ colors['green'] }}<br>
            blue    = {{ colors['blue'] }}<br>
        </div>
        
        
        
</body>
</html>