
<!DOCTYPE html>
<html>
<head>
<meta charset="${encoding}">
<title>Insert title here</title>
</head>
<body>


    
    <b>Escape e: </b>
    {{ '<h1>Escape e</h1>' | e }}                   {# <h1>Escape e</h1> #}
    <hr>
    
    
    <b>Escape escape: </b>
    {{ '<h3>Escape escape</h3>' | escape  }}        {# <h3>Escape escape</h3> #}
    <hr>
    
    
    <b>Escape attribute: </b>
    <table width=" {{  '"><h1>Attack attribute html</table>' | escape_attr }} ">
        <tr>
            <td>Attack attribute html</td>
        </tr>
    </table>
    <hr>
    
    <b>Escape css: </b>
    <a style="color: {{ '"><script>alert(1)</script><a href="#' | escape_css}}">escape css</a>
    <hr>
    
     <b>Escape escape_js: </b>
        <script>document.title =  '{{ "'; alert(100); var x='" | escape_js }}'</script> 
    <hr>
    
</body>
</html>