<style type="text/css">
	h5 {color:blue}	
</style>

<form name="main-form" id="main-form" action="#" method="post" style="margin-left: 20px;">

	<h5>NUMBER (IE - FF - Chrome - Safari - Opera)</h5>
	<input type="number" name="my-number" min="0" max="10">
	
	<h5>DATE (Chrome - Safari - Opera)</h5>
	<input type="date" name="my-date" max="2020-01-01" min="2000-01-01">
	
	<h5>COLOR (FF - Chrome - Opera)</h5>
	<input type="color" name="my-color">  
	
	<h5>RANGE (IE - FF - Chrome - Safari - Opera)</h5>
	<input type="range" name="my-range-01" min="0" max="1">
	<input type="range" name="my-range-01" min="0" max="100" value="90">
	
	<h5>MONTH (Chrome - Safari - Opera)</h5>
	<input type="month" name="my-month">
	
	<h5>WEEK (Chrome - Safari - Opera)</h5>
	<input type="week" name="my-week">
	
	<h5>TIME (Chrome - Safari - Opera)</h5>
	<input type="time" name="my-time">
	
	<h5>DATETIME (Safari - Opera)</h5>
	<input type="datetime" name="my-datetime">
	
	<h5>DATETIMELOCAL(Chrome - Safari - Opera)</h5>
	<input type="datetime-local" name="my-datetimelocal">
	
	<h5>EMAIL(IE - FF - Chrome - Opera)</h5>
  	<input type="email" name="my-email">
	
	<h5>SEARCH (Chrome - Safari)</h5>
	<input type="search" name="my-search">
	
	<h5>TEL</h5>
	<input type="tel" name="my-tel">
	
	<h5>URL (IE - FF - Chrome - Opera)</h5>
	<input type="url" name="my-url">
	
	
	<h5>SUBMIT FORM</h5>
	<input type="submit" value="Submit form">
	
</form>







